#!/usr/bin/env bash

CURSOR_APP_DIR=${CURSOR_APP_DIR:-"$HOME/apps/"}
#List separated by colons
CURSOR_REPOS=${CURSOR_REPOS:-"$HOME/repos/"}
CURSOR_EXTRA_BINDS=${CURSOR_EXTRA_BINDS:-""}
CURSOR_EXTRA_RO_BINDS=${CURSOR_EXTRA_RO_BINDS:-""}

filter=false

debug_filter=true
dbus_system_bus_socket="/run/dbus/system_bus_socket"
dbus_socket_for_cursor="/run/dbus/system_bus_socket"


if [[ ${1:-""} == "--dbus-filter" ]]; then
    shift
    filter=true
    dbus_socket_for_cursor="/run/user/${UID}/system_bus_socket-cusor-filtered"
fi

if $filter; then
    echo "setting up dbus proxy"
    if $debug_filter; then
        echo "logging enabled"
        xdg-dbus-proxy "unix:path=$dbus_system_bus_socket" "$dbus_socket_for_cursor" --log > dbus-cursor.log &
    else
        xdg-dbus-proxy "unix:path=$dbus_system_bus_socket" "$dbus_socket_for_cursor" &
    fi

    pid=$!
    sleep 1

    if ! [[ -e "$dbus_socket_for_cursor" ]]; then
        echo "socket: $dbus_socket_for_cursor could not be created"
        exit 1
    fi

    # Set up trap to clean up on exit
    cleanup() {
        echo "Stopping xdg-dbus-proxy..."
        kill $pid
        rm "$dbus_socket_for_cursor"
    }
    trap cleanup EXIT
fi

IFS=':' read -ra parts <<< "$CURSOR_REPOS"
repos=()
for part in "${parts[@]}"; do
    repos+=( --bind "$part" "$part")
done

IFS=':' read -ra parts <<< "$CURSOR_EXTRA_BINDS"
extra_binds=()
for part in "${parts[@]}"; do
    extra_binds+=( --bind "$part" "$part")
done

IFS=':' read -ra parts <<< "$CURSOR_EXTRA_RO_BINDS"
extra_ro_binds=()
for part in "${parts[@]}"; do
    extra_ro_binds+=( --ro-bind "$part" "$part")
done

bwrap --share-net \
      --unshare-pid \
      --new-session \
      --dev /dev \
      --tmpfs /tmp \
      --proc /proc \
      \
      --bind /run/user/$UID /run/user/$UID \
      --bind "$dbus_socket_for_cursor" "$dbus_system_bus_socket" \
      \
      --ro-bind /bin /bin \
      --ro-bind /usr /usr \
      --ro-bind /lib /lib \
      --ro-bind /lib64 /lib64 \
      --ro-bind /etc /etc \
      \
      --tmpfs /etc/.git \
      --ro-bind /dev/null /etc/passwd \
      --ro-bind /dev/null /etc/group \
      --ro-bind /dev/null /etc/shadow \
      \
      --bind "$CURSOR_APP_DIR/squashfs-root" /cursor \
      --bind $HOME/.config/Cursor $HOME/.config/Cursor \
      --bind $HOME/.cursor $HOME/.cursor \
      "${repos[@]}" \
      "${extra_binds[@]}" \
      -- \
      /cursor/AppRun
      "$@"
